import type { Campus, FoodStall, Meal, Review } from '../types';

export const CAMPUSES: Campus[] = [
  { id: 'ust', name: 'UST', fullName: 'University of Santo Tomas', location: 'España Blvd, Sampaloc, Manila' },
  { id: 'feu', name: 'FEU', fullName: 'Far Eastern University', location: 'Nicanor Reyes St, Sampaloc, Manila' },
  { id: 'ue', name: 'UE', fullName: 'University of the East', location: 'Claro M. Recto Ave, Sampaloc, Manila' },
  { id: 'nu', name: 'NU', fullName: 'National University', location: 'M.F. Jhocson St, Sampaloc, Manila' },
  { id: 'ceu', name: 'CEU', fullName: 'Centro Escolar University', location: 'Mendiola St, San Miguel, Manila' },
  { id: 'sanbeda', name: 'San Beda', fullName: 'San Beda University', location: 'Mendiola St, San Miguel, Manila' }
];

export const CATEGORIES = [
  'Rice Meals',
  'Noodles/Pasta',
  'Snacks & Street Food',
  'Drinks & Desserts',
  'Sandwiches & Bakery'
];

export const BUDGET_TIERS = [
  { id: 'under-50', label: 'Under ₱50', max: 50 },
  { id: '50-75', label: '₱50–₱75', min: 50, max: 75 },
  { id: '75-100', label: '₱75–₱100', min: 75, max: 100 },
  { id: 'above-100', label: 'Above ₱100', min: 100 }
];

export const FOOD_STALLS: FoodStall[] = [
  {
    id: 'ang-kong',
    name: 'Angkong Dimsum House',
    description: 'The ultimate student favorite for delicious, affordable siomai rice with sweet chili sauce.',
    campusId: 'ust',
    distance: '3 mins walk',
    distanceMeters: 180,
    categories: ['Rice Meals', 'Snacks & Street Food'],
    image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=600&auto=format&fit=crop&q=80',
    rating: 4.8,
    reviewsCount: 142,
    googleMapsUrl: 'https://maps.google.com/?q=Angkong+Dimsum+House+P.+Noval+UST',
    openingHours: '9:00 AM - 8:00 PM',
    menuItemIds: ['angkong-siomai-pork', 'angkong-siomai-chicken', 'angkong-dumplings']
  },
  {
    id: 'ate-ricas',
    name: "Ate Rica's Bacsilog",
    description: 'Famous bacsilog loaded with cheese sauce, liquid seasoning, and crunchy bacon bits.',
    campusId: 'ust',
    distance: '2 mins walk',
    distanceMeters: 120,
    categories: ['Rice Meals'],
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600&auto=format&fit=crop&q=80',
    rating: 4.6,
    reviewsCount: 98,
    googleMapsUrl: 'https://maps.google.com/?q=Ate+Ricas+Bacsilog+Asturias+UST',
    openingHours: '7:00 AM - 9:00 PM',
    menuItemIds: ['ate-ricas-bacon', 'ate-ricas-tapa', 'ate-ricas-combo']
  },
  {
    id: 'dimsum-treats',
    name: 'Dimsum Treats',
    description: 'Generous servings of steam/fried dimsum and larger-than-average siomai at budget rates.',
    campusId: 'ust',
    distance: '5 mins walk',
    distanceMeters: 300,
    categories: ['Rice Meals', 'Snacks & Street Food'],
    image: 'https://images.unsplash.com/photo-1496116211227-7d3ccb8f4b74?w=600&auto=format&fit=crop&q=80',
    rating: 4.5,
    reviewsCount: 84,
    googleMapsUrl: 'https://maps.google.com/?q=Dimsum+Treats+Dapitan+UST',
    openingHours: '8:00 AM - 10:00 PM',
    menuItemIds: ['dimsum-siomai-rice', 'dimsum-sharkfin-rice']
  },
  {
    id: 'hepaslane-burgers',
    name: 'Hepaslane Street Grill',
    description: 'Affordable flame-grilled burgers, footlong hotdogs, and street skewers right outside the gate.',
    campusId: 'feu',
    distance: '1 min walk',
    distanceMeters: 50,
    categories: ['Sandwiches & Bakery', 'Snacks & Street Food'],
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80',
    rating: 4.2,
    reviewsCount: 56,
    googleMapsUrl: 'https://maps.google.com/?q=Gastambide+Street+FEU+Manila',
    openingHours: '10:00 AM - 11:00 PM',
    menuItemIds: ['hepaslane-burger-cheese', 'hepaslane-footlong']
  },
  {
    id: 'lola-elenas',
    name: "Lola Elena's Pancit & Lugawan",
    description: 'Hearty bowls of lugaw, tokwa’t baboy, and loaded pancit cantoon, cooked home-style.',
    campusId: 'feu',
    distance: '4 mins walk',
    distanceMeters: 250,
    categories: ['Noodles/Pasta', 'Snacks & Street Food'],
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=600&auto=format&fit=crop&q=80',
    rating: 4.4,
    reviewsCount: 37,
    googleMapsUrl: 'https://maps.google.com/?q=Nicanor+Reyes+FEU+Manila',
    openingHours: '6:00 AM - 8:00 PM',
    menuItemIds: ['lola-elena-lugaw', 'lola-elena-pancit']
  },
  {
    id: 'mendiola-siomai',
    name: 'Mendiola Siomai & Fried Rice',
    description: 'Classic student station on Mendiola Bridge for quick, steaming hot siomai packs.',
    campusId: 'ceu',
    distance: '2 mins walk',
    distanceMeters: 100,
    categories: ['Rice Meals', 'Snacks & Street Food'],
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&auto=format&fit=crop&q=80',
    rating: 4.3,
    reviewsCount: 63,
    googleMapsUrl: 'https://maps.google.com/?q=Mendiola+Street+Manila',
    openingHours: '7:30 AM - 7:30 PM',
    menuItemIds: ['mendiola-siomai-rice-combo', 'mendiola-gulaman']
  },
  {
    id: 'beda-diners',
    name: 'Beda Red Diners',
    description: 'Cozy cafeteria annex serving sizzling pork sisig and garlic fried rice to San Beda students.',
    campusId: 'sanbeda',
    distance: '3 mins walk',
    distanceMeters: 150,
    categories: ['Rice Meals'],
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600&auto=format&fit=crop&q=80',
    rating: 4.5,
    reviewsCount: 49,
    googleMapsUrl: 'https://maps.google.com/?q=San+Beda+University+Mendiola+Manila',
    openingHours: '8:00 AM - 6:00 PM',
    menuItemIds: ['beda-red-sisig', 'beda-red-chix']
  }
];

export const MEALS: Meal[] = [
  {
    id: 'angkong-siomai-pork',
    name: 'Pork Siomai Rice (4 pcs)',
    price: 55,
    description: 'Pork siomai topped with homemade chili garlic oil and sweet soy sauce over a mountain of steaming white rice.',
    stallId: 'ang-kong',
    stallName: 'Angkong Dimsum House',
    campusId: 'ust',
    category: 'Rice Meals',
    image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=500&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewsCount: 104,
    lastUpdated: '2026-06-28T12:00:00Z',
    tags: ['50-75']
  },
  {
    id: 'angkong-siomai-chicken',
    name: 'Chicken Siomai Rice (4 pcs)',
    price: 55,
    description: 'Tender chicken siomai with aromatic garlic sauce and steamed white rice. A lighter but equally delicious option.',
    stallId: 'ang-kong',
    stallName: 'Angkong Dimsum House',
    campusId: 'ust',
    category: 'Rice Meals',
    image: 'https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?w=500&auto=format&fit=crop&q=80',
    rating: 4.7,
    reviewsCount: 22,
    lastUpdated: '2026-06-29T10:30:00Z',
    tags: ['50-75']
  },
  {
    id: 'angkong-dumplings',
    name: 'Fried Dumplings Rice',
    price: 65,
    description: 'Crispy fried gyoza-style dumplings served with rice and sweet-sour dynamic dipping sauce.',
    stallId: 'ang-kong',
    stallName: 'Angkong Dimsum House',
    campusId: 'ust',
    category: 'Rice Meals',
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=500&auto=format&fit=crop&q=80',
    rating: 4.8,
    reviewsCount: 16,
    lastUpdated: '2026-06-25T14:20:00Z',
    tags: ['50-75']
  },
  {
    id: 'ate-ricas-bacon',
    name: 'Bacon Bacsilog',
    price: 69,
    description: "Crispy bacon strips, a sunny-side-up egg, and Ate Rica's famous signature yellow cheese and liquid seasoning over garlic rice.",
    stallId: 'ate-ricas',
    stallName: "Ate Rica's Bacsilog",
    campusId: 'ust',
    category: 'Rice Meals',
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=500&auto=format&fit=crop&q=80',
    rating: 4.7,
    reviewsCount: 73,
    lastUpdated: '2026-06-30T09:15:00Z',
    tags: ['50-75']
  },
  {
    id: 'ate-ricas-tapa',
    name: 'Tapsilog (Beef Tapa)',
    price: 85,
    description: 'Premium marinated beef strips with a fried egg and double-cheese sauce on garlic rice.',
    stallId: 'ate-ricas',
    stallName: "Ate Rica's Bacsilog",
    campusId: 'ust',
    category: 'Rice Meals',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500&auto=format&fit=crop&q=80',
    rating: 4.5,
    reviewsCount: 20,
    lastUpdated: '2026-06-29T11:45:00Z',
    tags: ['75-100']
  },
  {
    id: 'ate-ricas-combo',
    name: 'Super Bacsilog Combo',
    price: 110,
    description: 'Ultimate loaded platter featuring bacon, burger patty, hotdog, and double eggs smothered in melted cheese sauce.',
    stallId: 'ate-ricas',
    stallName: "Ate Rica's Bacsilog",
    campusId: 'ust',
    category: 'Rice Meals',
    image: 'https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=500&auto=format&fit=crop&q=80',
    rating: 4.4,
    reviewsCount: 5,
    lastUpdated: '2026-06-24T15:30:00Z',
    tags: ['above-100']
  },
  {
    id: 'dimsum-siomai-rice',
    name: 'Steamed Pork Siomai Rice',
    price: 49,
    description: '4 oversized pieces of savory pork siomai, fried garlic bits, and plain rice. The ultimate budget-saver under 50 pesos!',
    stallId: 'dimsum-treats',
    stallName: 'Dimsum Treats',
    campusId: 'ust',
    category: 'Rice Meals',
    image: 'https://images.unsplash.com/photo-1496116211227-7d3ccb8f4b74?w=500&auto=format&fit=crop&q=80',
    rating: 4.6,
    reviewsCount: 65,
    lastUpdated: '2026-06-30T10:00:00Z',
    tags: ['under-50']
  },
  {
    id: 'dimsum-sharkfin-rice',
    name: 'Sharkfin Dumpling Rice',
    price: 52,
    description: 'Deliciously wrapped pork and seafood sharkfin dumplings (4 pcs) with sweet chili oil and hot rice.',
    stallId: 'dimsum-treats',
    stallName: 'Dimsum Treats',
    campusId: 'ust',
    category: 'Rice Meals',
    image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=500&auto=format&fit=crop&q=80',
    rating: 4.4,
    reviewsCount: 19,
    lastUpdated: '2026-06-27T08:00:00Z',
    tags: ['50-75']
  },
  {
    id: 'hepaslane-burger-cheese',
    name: 'Double Cheese Street Burger',
    price: 45,
    description: 'Juicy local beef patty grill-fried on the spot, topped with cheddar slices, cabbage, and sweet dressing.',
    stallId: 'hepaslane-burgers',
    stallName: 'Hepaslane Street Grill',
    campusId: 'feu',
    category: 'Sandwiches & Bakery',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500&auto=format&fit=crop&q=80',
    rating: 4.3,
    reviewsCount: 42,
    lastUpdated: '2026-06-30T14:00:00Z',
    tags: ['under-50']
  },
  {
    id: 'hepaslane-footlong',
    name: 'Gastambide Footlong Hotdog',
    price: 70,
    description: 'A 12-inch grilled hotdog in a soft bun, loaded with yellow mustard, ketchup, and grated cheese.',
    stallId: 'hepaslane-burgers',
    stallName: 'Hepaslane Street Grill',
    campusId: 'feu',
    category: 'Sandwiches & Bakery',
    image: 'https://images.unsplash.com/photo-1619740455993-9e612b1af08a?w=500&auto=format&fit=crop&q=80',
    rating: 4.1,
    reviewsCount: 14,
    lastUpdated: '2026-06-21T18:00:00Z',
    tags: ['50-75']
  },
  {
    id: 'lola-elena-lugaw',
    name: 'Special Lugaw with Egg',
    price: 35,
    description: 'Comforting, steaming hot Filipino rice porridge topped with toasted garlic, spring onions, and a hard-boiled egg.',
    stallId: 'lola-elenas',
    stallName: "Lola Elena's Pancit & Lugawan",
    campusId: 'feu',
    category: 'Snacks & Street Food',
    image: 'https://images.unsplash.com/photo-1594911774802-8822a707caff?w=500&auto=format&fit=crop&q=80',
    rating: 4.5,
    reviewsCount: 22,
    lastUpdated: '2026-06-29T06:30:00Z',
    tags: ['under-50']
  },
  {
    id: 'lola-elena-pancit',
    name: 'Pancit Canton Big Plate',
    price: 45,
    description: 'A huge portion of stir-fried canton noodles with shredded vegetables and sliced fishballs. Extremely filling.',
    stallId: 'lola-elenas',
    stallName: "Lola Elena's Pancit & Lugawan",
    campusId: 'feu',
    category: 'Noodles/Pasta',
    image: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?w=500&auto=format&fit=crop&q=80',
    rating: 4.3,
    reviewsCount: 15,
    lastUpdated: '2026-06-28T09:00:00Z',
    tags: ['under-50']
  },
  {
    id: 'mendiola-siomai-rice-combo',
    name: 'Mendiola Siomai Rice (5 pcs)',
    price: 50,
    description: 'Budget student favorite featuring five mixed pork/beef siomai, unlimited chili garlic paste, and fried rice.',
    stallId: 'mendiola-siomai',
    stallName: 'Mendiola Siomai & Fried Rice',
    campusId: 'ceu',
    category: 'Rice Meals',
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=500&auto=format&fit=crop&q=80',
    rating: 4.4,
    reviewsCount: 51,
    lastUpdated: '2026-06-30T11:00:00Z',
    tags: ['under-50']
  },
  {
    id: 'mendiola-gulaman',
    name: 'Giant Samalamig / Gulaman',
    price: 15,
    description: 'Tall glass of sweet, refreshing iced brown sugar drink with chewy gelatin cubes.',
    stallId: 'mendiola-siomai',
    stallName: 'Mendiola Siomai & Fried Rice',
    campusId: 'ceu',
    category: 'Drinks & Desserts',
    image: 'https://images.unsplash.com/photo-1497534446932-c925b458314e?w=500&auto=format&fit=crop&q=80',
    rating: 4.2,
    reviewsCount: 12,
    lastUpdated: '2026-06-25T13:00:00Z',
    tags: ['under-50']
  },
  {
    id: 'beda-red-sisig',
    name: 'Sizzling Pork Sisig Rice',
    price: 89,
    description: 'Crispy, seasoned pork sisig topped with raw egg, green chili, and citrus calamansi, served with garlic fried rice.',
    stallId: 'beda-diners',
    stallName: 'Beda Red Diners',
    campusId: 'sanbeda',
    category: 'Rice Meals',
    image: 'https://images.unsplash.com/photo-1608897013039-887f21d8c804?w=500&auto=format&fit=crop&q=80',
    rating: 4.6,
    reviewsCount: 38,
    lastUpdated: '2026-06-30T12:30:00Z',
    tags: ['75-100']
  },
  {
    id: 'beda-red-chix',
    name: 'Crispy Red Chicken Poppers',
    price: 75,
    description: 'Bite-sized chicken chunks double-fried to a golden crunch, coated in sweet glazed sauce and served over rice.',
    stallId: 'beda-diners',
    stallName: 'Beda Red Diners',
    campusId: 'sanbeda',
    category: 'Rice Meals',
    image: 'https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=500&auto=format&fit=crop&q=80',
    rating: 4.4,
    reviewsCount: 11,
    lastUpdated: '2026-06-28T14:40:00Z',
    tags: ['50-75']
  }
];

export const REVIEWS: Review[] = [
  {
    id: 'r1',
    userId: 'u1',
    userName: 'Juan Dela Cruz',
    targetId: 'angkong-siomai-pork',
    targetType: 'meal',
    rating: 5,
    comment: 'Angkong siomai is the best in U-Belt! Best paired with extra chili. Still ₱55 as of June, absolute bargain.',
    budgetFeedback: 'Still ₱55 as of June.',
    createdAt: '2026-06-28T14:00:00Z'
  },
  {
    id: 'r2',
    userId: 'u2',
    userName: 'Maria Santos',
    targetId: 'ate-ricas-bacon',
    targetType: 'meal',
    rating: 4,
    comment: 'Cheesy and bacony goodness! Sometimes the line takes 10 minutes but totally worth it. Price is now ₱69.',
    budgetFeedback: 'Updated to ₱69.',
    createdAt: '2026-06-30T09:30:00Z'
  },
  {
    id: 'r3',
    userId: 'u3',
    userName: 'Mark Aquino',
    targetId: 'dimsum-siomai-rice',
    targetType: 'meal',
    rating: 5,
    comment: 'You can never go wrong with 4 big pieces of siomai under ₱50. Perfect for petsa de peligro.',
    budgetFeedback: 'Still ₱49.',
    createdAt: '2026-06-30T10:15:00Z'
  },
  {
    id: 'r4',
    userId: 'u4',
    userName: 'Kyle FEU',
    targetId: 'hepaslane-burger-cheese',
    targetType: 'meal',
    rating: 4,
    comment: 'Classic Gastambide burger. Tastes amazing for its price, although the area is a bit crowded.',
    budgetFeedback: 'P45 super cheap.',
    createdAt: '2026-06-30T14:10:00Z'
  }
];
